bot/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url
from django.views import generic
from . import views



app_name="ioe"    #called namespacing of urls,,,so as to distinguish between similar named urls#of different apps
urlpatterns=[
    path(r'home',views.Template.as_view(),name="itsourearth"),
    path('contact',views.contactus,name="contact"),
    path('',views.redirect,name="red"),
    # path('try',views.TryTemplate.as_view(),name="modal"),
]

chatbot/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("bot.urls")),
]

bot/models.py
from django.db import models
import datetime
from django.utils import timezone

class contact_us(models.Model):
    name = models.CharField(max_length=70)
    email=models.EmailField(default="aaa@bb.c")
    phone=models.CharField(default='xxxxxxxxxx',max_length=70)
    message=models.CharField(max_length=500)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)

    def __str__(self):
    	return self.name

bot/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import contact_us as cu
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import datetime

import smtplib
from email.mime.text import MIMEText


class Template(generic.TemplateView):
    template_name="bot/index.html"

# class TryTemplate(generic.TemplateView):
#     template_name="bot/modaltemp.html"

def contactus(request):

    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        phone=request.POST['phone']
        message=request.POST['message']

        val=0
        count=0
        error_name=''
        error_message=''
        error_email=''
        error_phone=''
        if name=='':
            error_name="Please enter your name."
            count+=1

        if email=='':
            error_email="Please enter your email address."
            count+=1

        if phone=='':
            error_phone="Please enter your phone number."
            count+=1
        else:
            if len(phone)<10 or len(phone)>11 or not all(i.isdigit for i in phone)::
                error_phone="Please enter a valid contact number"
                count+=1

        if message=='':
            error_message="Please enter a message."
            count+=1

        if count==0:
            entry=cu(name=name,email=email,phone=phone,message=message)
            entry.save()      
            val=0
            print('====================================================================== %d'%val)
            return render(request,'bot/child.html',{'error_name':error_name,'error_phone':error_phone,'error_message':error_message,'error_email':error_email,'val':val}) 
        if count>0:
            val=1
            return render(request,"bot/child.html",{'error_name':error_name,'error_phone':error_phone,'error_message':error_message,'error_email':error_email,'val':val,'name_val':name,'email_val':email,'phone_val':phone,'message_val':message})

    else:
        return render(request,"bot/index.html")

def redirect(request):
    return HttpResponseRedirect('/home')

    # class Template(generic.TemplateView):
    #     template_name="bot/index.html"












# def sendmail(request):
    
#     if request.method=='POST':
#         name=request.POST['name']
#         email=request.POST['email']
#         phone=request.POST['phone']
#         message=request.POST['message']

#         count=0
#         error_name=''
#         error_message=''
#         error_email=''
#         error_phone=''
#         if name=='':
#             error_name="Please enter your name."
#             count+=1

#         if email=='':
#             error_email="Please enter your email address."
#             count+=1

#         if phone=='':
#             error_phone="Please enter your phone number."
#             count+=1
#         else:
#             if len(phone)<10 or len(phone)>10:
#                 error_phone="Please enter a valid contact number"
#                 count+=1

#         if message=='':
#             error_message="Please enter a message."
#             count+=1

#         if count==0:
#             body=message                                        #pass the html syntax
#             sender="aman.parmar17@gmail.com"
#             receiver="itsourearth2016@gmail.com"

#             msg=MIMEText(body)
#             msg["From"]=sender
#             msg["To"]=receiver
#             msg["Subject"]="contact made"

#             ss=smtplib.SMTP("smtp.gmail.com",587)
#             ss.starttls()
#             ss.login("aman.parmar17@gmail.com","aman.parmar17")

#             ss.send_message(msg)
#             print("mail sent")
#             ss.quit()

#             return HttpResponseRedirect('/home') 
#         return render(request,"bot/child.html",{'error_name':error_name,'error_phone':error_phone,'error_message':error_message,'error_email':error_email})

#     else:
#         return render(request,"bot/index.html")

    

bot/templates/bot/child.html
{% extends 'bot/index.html' %}

{% if error_name %}
    {% block name %}
        <b><p class="help-block text-danger"> {{ error_name }} </p></b>
    {% endblock %}
{% endif %}

{% if error_email %}
    {% block email %} 
        <b><p class="help-block text-danger">{{ error_email }}</p></b>
    {% endblock %}
{% endif %}

{% if error_phone %}
    {% block phone %} 
        <b><p class="help-block text-danger">{{ error_phone}}</p></b>
    {% endblock %}
{% endif %}

{% if error_message %}
    {% block message %} 
        <b><p class="help-block text-danger"> {{ error_message}} </p></b>
    {% endblock %}
{% endif %}

<!-- {% block model%}
    <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#portfolioModal1">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"> Thank you for contacting us..</i>
            </div>
          </div>
        </a>
    </div>
{% endblock %} -->

    {% block extra_js %}
    {% if not val %}

        <!-- Modal Message -->
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#portfolioModalmess').modal('show');
            });
        </script>
        {% endif %}
    {% endblock %}


{% block modal %}
    {% if not val %}
        <div class="portfolio-modal modal fade" id="portfolioModalmess" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <!-- <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                    <div class="rl"></div>
                    </div>
                </div> -->
                <div class="container">
                    <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <div class="modal-body">
                        <!-- Project Details Go Here -->
                        <h2 class="text-uppercase">Thank You for Reaching Us !</h2>
                        <p class="item-intro text-muted">We Will Get Back Toyou As Soon As We can.</p>
                        <form action='{% url 'ioe:red' %}' method='post'>
                            {% csrf_token %}
                            <button class="btn btn-primary"  type="submit">
                                <i class="fa fa-times"></i>
                                Go to home!</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
    {% endif %}
{% endblock %}

{% block errors %}
    {% if val %}
        <script type="text/javascript">
    // $("a").click(function(){
                // $(window).on('load',function(){
                    
                // });
               
				var scroll= $(window).scrollTop();
                console.log(scroll)
                var x = $('#contact').position().top;
                if (x){
                    console.log(x)
                }
                else{
                    console.log("error in reading the val")
                }
				scroll= scroll+ x;
                console.log(scroll)
				$('html, body').animate({
					scrollTop: scroll
				}, 500);

        </script>
    {% endif %}
{% endblock%}

{% block value_name%}
    {% if val and not error_name %}
            value=  {{ name_val }}
    {% endif%}
{% endblock %}

{% block value_email %}
    {% if val and not error_email %}
        value={{ email_val }}
    {% endif%}
{% endblock %}

{% block value_phone%}
    {% if val and not error_phone %}
        value={{ phone_val }}
    {% endif%}
{% endblock %}

{% block value_message%}
    {% if val and not error_message %}
        {{ message_val }}
    {% endif%}
{% endblock %}

bot/templates/bot/modaltemp.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>It's Our Earth</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link href="{% static 'bot/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'bot/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'bot/css/agency.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">



        <div class="portfolio-modal modal fade" id="portfolioModalmess" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="close-modal" data-dismiss="modal">
                      <div class="lr">
                        <div class="rl"></div>
                      </div>
                    </div>
                    <div class="container">
                      <div class="row">
                        <div class="col-lg-8 mx-auto">
                          <div class="modal-body">
                            <!-- Project Details Go Here -->
                            <h2 class="text-uppercase">Thank You for Reaching Us !</h2>
                            <p class="item-intro text-muted">We Will Get Back Toyou As Soon As We can.</p>
                            
                            <button class="btn btn-primary" data-dismiss="modal" type="button">
                              <i class="fa fa-times"></i>
                              Go to home!</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          

        <div class="col-lg-12 text-center">
                <div id="success"></div>
                <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit"><a class="btn btn-primary btn-xl portfolio-link" data-toggle="modal" href="#portfolioModalmess">Send Message</a></button>
        </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'bot/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bot/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'bot/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact form JavaScript -->
    <!-- <script src="{% static 'bot/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'bot/js/contact_me.js' %}"></script> -->

    <!-- Custom scripts for this template -->
    <script src="{% static 'bot/js/agency.min.js' %}"></script>
    <script src="{% static 'bot/modalwork.js' %}"></script>

    </body>

    </html>